language: node_js
node_js:
- stable
install:
#- npm install
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config # trust host
#script:
#- npm pack
before_install:
- chmod +x .travis/deploy.sh
- ls -l .travis/deploy.sh
- openssl aes-256-cbc -K $encrypted_4df64db2b58d_key -iv $encrypted_4df64db2b58d_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
#git config --global push.default matching
