language: node_js
node_js:
- stable
install:
  - echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_install:
- openssl aes-256-cbc -K $encrypted_4df64db2b58d_key -iv $encrypted_4df64db2b58d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- eval "$(ssh-agent -s)" #start the ssh agent
- chmod 600 ~/.ssh/id_rsa # this key should have push access
- ssh-add ~/.ssh/id_rsa
- git remote add deploy ssh://git@$IP:$PORT$DEPLOY_DIR
- git push deploy
