language: node_js
node_js:
- stable
install:
- npm install
script:
- npm pack
before_install:
- openssl aes-256-cbc -K $encrypted_4df64db2b58d_key -iv $encrypted_4df64db2b58d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- yes | bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
